#!/usr/bin/env bash
# Atlas global launcher installer.
# Installs `atlas` (Ink CLI) and `atlas-bot` (Discord bot) into ~/.local/bin.
# Re-run this any time you want to refresh the launchers (it's idempotent).

set -e

ATLAS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INK_LAUNCHER="${ATLAS_DIR}/cli-ink/atlas-ink"
BOT_LAUNCHER="${ATLAS_DIR}/cli-ink/atlas-bot"
BIN_DIR="${HOME}/.local/bin"
ATLAS_CMD="${BIN_DIR}/atlas"
ATLAS_BOT_CMD="${BIN_DIR}/atlas-bot"

if [ ! -x "${INK_LAUNCHER}" ]; then
  echo "✗ ${INK_LAUNCHER} is missing or not executable."
  echo "  Run: chmod +x \"${INK_LAUNCHER}\""
  exit 1
fi

if [ ! -x "${BOT_LAUNCHER}" ]; then
  echo "✗ ${BOT_LAUNCHER} is missing or not executable."
  echo "  Run: chmod +x \"${BOT_LAUNCHER}\""
  exit 1
fi

mkdir -p "${BIN_DIR}"

cat > "${ATLAS_CMD}" << EOF
#!/usr/bin/env bash
# Atlas CLI launcher (auto-generated by install.sh) — runs the Ink/React rewrite.
exec "${INK_LAUNCHER}" "\$@"
EOF
chmod +x "${ATLAS_CMD}"

cat > "${ATLAS_BOT_CMD}" << EOF
#!/usr/bin/env bash
# Atlas Discord bot launcher (auto-generated by install.sh).
exec "${BOT_LAUNCHER}" "\$@"
EOF
chmod +x "${ATLAS_BOT_CMD}"

echo "✓ atlas       → ${ATLAS_CMD}"
echo "✓ atlas-bot   → ${ATLAS_BOT_CMD}"
echo "  points to:"
echo "    ${INK_LAUNCHER}"
echo "    ${BOT_LAUNCHER}"

if ! echo ":${PATH}:" | grep -q ":${BIN_DIR}:"; then
  echo ""
  echo "⚠  ${BIN_DIR} is not on your PATH."
  echo "   Add this line to your shell profile (~/.zshrc or ~/.bashrc):"
  echo ""
  echo "       export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  echo "   Then restart your terminal, or run: source ~/.zshrc"
else
  echo ""
  echo "Open a new terminal and try:"
  echo "  atlas       — launch the CLI"
  echo "  atlas-bot   — start the Discord bot"
fi
