#!/usr/bin/env bash
# Atlas global launcher installer
# Creates ~/.local/bin/atlas so you can run "atlas" from any directory.

set -e

ATLAS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/atlas"

mkdir -p "${BIN_DIR}"

cat > "${LAUNCHER}" << EOF
#!/usr/bin/env bash
# Atlas launcher (auto-generated by install.sh)
exec python3 "${ATLAS_DIR}/main.py" "\$@"
EOF

chmod +x "${LAUNCHER}"

echo "✓ atlas installed → ${LAUNCHER}"
echo "✓ points to       → ${ATLAS_DIR}"

if ! echo ":${PATH}:" | grep -q ":${BIN_DIR}:"; then
  echo ""
  echo "⚠  ${BIN_DIR} is not on your PATH."
  echo "   Add this line to your shell profile (~/.zshrc or ~/.bashrc):"
  echo ""
  echo "       export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  echo "   Then restart your terminal, or run: source ~/.zshrc"
else
  echo ""
  echo "Open a new terminal and type: atlas"
fi
